name: youqiflutter
version: 1.0.0+1
publish_to: none
description: base on youqi
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  dio: ^4.0.4
  json_serializable: ^6.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

